version: 2

updates:
# keep up to date the github-actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly

# enable go dependencies security updates
- directory: /
  open-pull-requests-limit: 0
  package-ecosystem: gomod
  rebase-strategy: auto
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/Rome
